name: Build OpenVision IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0 # Скачиваем всю историю коммитов

      - name: Reset to stable commit
        run: |
          # Откатываемся на стабильную версию приложения до внедрения ломающих Swift-пакетов
          git reset --hard 2df39c15865239a5ec65a12001e3e7f415951a89 || git reset --hard HEAD~15

      - name: Create Config File
        run: |
          echo "DEVELOPMENT_TEAM = 1234567890" > Config.xcconfig
          echo "META_APP_ID = 1234567890" >> Config.xcconfig

      - name: Build and Archive
        run: |
          xcodebuild archive \
            -project OpenVision.xcodeproj \
            -scheme OpenVision \
            -configuration Release \
            -archivePath $PWD/build/OpenVision.xcarchive \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
            
      - name: Create Unsigned IPA
        run: |
          mkdir -p Payload
          cp -r build/OpenVision.xcarchive/Products/Applications/OpenVision.app Payload/
          zip -r OpenVision.ipa Payload
          
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenVision-Stable-IPA
          path: OpenVision.ipa
          retention-days: 5
